name: Publish Docker Image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - docker-compose.yml
      - README.md
      - LICENSE
jobs:
  build:
    name: build_docker_image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Generate metadata of original Left 4 Dead 2 Server Docker image
        id: original-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/l4d2server
          flavor: |
            latest=true
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=ref,event=tag
      - name: Build and push image of original Left 4 Dead 2 server
        uses: docker/build-push-action@v2
        with:
          context: ./original
          platforms: linux/amd64
          push: true
          tags: ${{ steps.original-meta.outputs.tags }}
